In [107]:
def hello():
    print("Hello, World!")
    

In [108]:
hello()

Hello, World!


## arrays 


In [109]:
import numpy as np

In [110]:
arr = np.array([1,2,3,5])
print(arr)

[1 2 3 5]


In [111]:
a = [1,5,6,"ankit",7.5]
print(a)

[1, 5, 6, 'ankit', 7.5]


In [112]:
np.array(a)

array(['1', '5', '6', 'ankit', '7.5'], dtype='<U32')

In [113]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [114]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [115]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [116]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [117]:
np.ones((4,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [118]:
np.linspace(0 ,1,100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [119]:
np.random.rand(10) # 1D array of 10 random numbers between 0 and 1

array([1.22487288e-01, 2.74207805e-01, 9.15285888e-01, 7.24616583e-01,
       4.14686010e-01, 1.18778197e-04, 5.26197921e-01, 8.74604368e-01,
       7.95953991e-02, 9.82951256e-01])

In [120]:
np.random.randn(10) # 1D array of 10 random numbers from standard normal distribution   

array([-1.61393155,  1.21279505,  0.17979273, -0.63573175,  2.03018915,
        1.64114393, -0.11562039,  0.91620188, -0.7600292 , -0.19988251])

In [121]:
np.random.randint(9) # 

2

In [ ]:
np.random.randint(10,20,20) #  

array([19, 11, 10, 17, 19, 13, 11, 12, 19, 13, 16, 10, 17, 11, 18, 14, 14,
       19, 17, 19])

In [123]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])


In [124]:
arr.shape

(3, 3)

In [125]:
arr.size

9

In [126]:
arr.dtype

dtype('int64')

In [127]:
arr.min()

np.int64(1)

In [128]:
arr.max()

np.int64(9)

In [129]:
arr.sum()

np.int64(45)

In [130]:
np.sum(arr, axis=0) # column wise sum

array([12, 15, 18])

In [131]:
np.sum(arr, axis=1) # column wise sum

array([ 6, 15, 24])

In [ ]:
arr.argmin()        # index of minimum element

np.int64(0)

In [133]:
arr.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])